// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 24.11.2025, 13:41:52
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Monst/Desktop/Projekt RentCar/nuxt-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Monst/Desktop/Projekt RentCar/nuxt-app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Monst/Desktop/Projekt RentCar/nuxt-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Monst/Desktop/Projekt RentCar/nuxt-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Monst/Desktop/Projekt RentCar/nuxt-app/plugins/**/*.{js,ts,mjs}","C:/Users/Monst/Desktop/Projekt RentCar/nuxt-app/composables/**/*.{js,ts,mjs}","C:/Users/Monst/Desktop/Projekt RentCar/nuxt-app/utils/**/*.{js,ts,mjs}","C:/Users/Monst/Desktop/Projekt RentCar/nuxt-app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Monst/Desktop/Projekt RentCar/nuxt-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Monst/Desktop/Projekt RentCar/nuxt-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Monst/Desktop/Projekt RentCar/nuxt-app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;